### ISSUE TITLE
Homework 3: Provided links are broken

### ISSUE THREAD

**Issue by dobijan** [bmeaut/python_nlp_2017_fall#8]
It seems to me that the links provided in the first exercise of the third homework are broken. The links:

1. http://sandbox.mokk.bme.hu/~ndavid/homework3/{neptun_code}/homework3_1_1_1.ipynb
2. http://sandbox.mokk.bme.hu/~ndavid/homework3/{neptun_code}/homework3_1_1_2.ipynb

I am aware of the NEPTUN code placeholder in the links. However, replacing it with my NEPTUN code is fruitless. Moreover, trying to snoop around in http://sandbox.mokk.bme.hu/~ndavid/ is also fruitless, there is no homework3 directory to look into.

Are the links dead despite the homework being handed out, or am I doing something wrong?

**Comment by dobijan** [comment]
I realized the NEPTUN codes in the links are not case insensitive. They need to be provided in ALL CAPS. Perhaps the placeholder should reflect this? For example: {NEPTUN_CODE_CAPITALIZED}

**Comment by DavidNemeskey** [comment]
Thanks for spotting this. It never occurred to me that
1. anyone would type their Neptun code in lower case
1. Apache respects the case sensitivity of the underlying file system.

Fixed now.
